#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# PATH handling tests

echo "--------------------------------------------"
echo "----------- NON-INTERACTIVE MODE -----------"
echo "--------------------------------------------"
echo
echo "TEST: Regular \"exit\""
echo "==========[sh]=========="
echo "exit" | sh
echo
echo "==========[hsh]========="
echo "exit" | ./hsh
echo
echo --------------------------------------------
echo "TEST: Trailing spaces \"exit    \""
echo "==========[sh]=========="
echo "exit    " | sh
echo
echo "==========[hsh]========="
echo "exit    " | ./hsh
echo
echo --------------------------------------------
echo "TEST: Leading spaces \"    exit\""
echo "==========[sh]=========="
echo "    exit" | sh
echo
echo "==========[hsh]========="
echo "    exit" | ./hsh
echo
echo
echo --------------------------------------------
echo "TEST: Leading and trailing tabs \"\texit\t\""
echo "==========[sh]=========="
echo "\texit\t" | sh
echo
echo "==========[hsh]========="
echo "\texit\t" | ./hsh
echo
echo
echo --------------------------------------------
echo "TEST: Multiple spaces and tabs \"\t   \t\t exit  \t\t  \t \""
echo "==========[sh]=========="
echo "\t   \t\t exit  \t\t  \t \"" | sh
echo
echo "==========[hsh]========="
echo "\t   \t\t exit  \t\t  \t \"" | ./hsh
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
