#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# strtok handling tests

echo "--------------------------------------------"
echo "------- WRITE CUSTOM STRTOK [TASK 6] ------"
echo "--------------------------------------------"
echo
echo "TEST: no strtok function was used"
echo "==============[sh]==============="
echo strace -c -o output.txt /sh | cat output.txt | grep strtok
echo
echo "==============[hsh]=============="
echo strace -c -o output.txt ./hsh | cat output.txt | grep strtok
echo
echo --------------------------------------------
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
