#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# getline handling tests

echo "--------------------------------------------"
echo "------- WRITE CUSTOM GETLINE [TASK 4] ------"
echo "--------------------------------------------"
echo
echo "TEST: \"/bin/ls\""
echo "==========[sh]=========="
echo "/bin/ls" | sh | $LTRACE -bco $LTRACEOUTPUTFILE $SHELL > $OUTPUTFILE | grep getline
echo
echo "==========[hsh]========="
echo "/bin/ls" | ./hsh | $LTRACE -bco $LTRACEOUTPUTFILE $SHELL > $OUTPUTFILE | grep getline
echo
echo --------------------------------------------
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
