#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# PATH handling tests

echo "--------------------------------------------"
echo "--------- HANDLE THE PATH [TASK 7] ---------"
echo "--------------------------------------------"
echo
echo "TEST: \"bin/ls\""
echo "==========[sh]=========="
echo "/bin/ls" | sh
echo
echo "==========[hsh]========="
echo "/bin/ls" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"ls\""
echo "==========[sh]=========="
echo "ls" | sh
echo
echo "==========[hsh]========="
echo "ls" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"ls /home\""
echo "==========[sh]=========="
echo "ls /home" | sh
echo
echo "==========[hsh]========="
echo "ls /home" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"/tmp/i_dont_exit\""
echo "==========[sh]=========="
echo "/tmp/i_dont_exit" | sh
echo
echo "==========[hsh]========="
echo "/tmp/i_dont_exit" | ./hsh
echo
echo
echo --------------------------------------------
echo "TEST: \"cat a.out.txt\""
echo "Hello, world!" > a.out.txt
echo "==========[sh]=========="
echo "cat a.out.txt" | sh
echo
echo "==========[hsh]========="
echo "cat a.out.txt" | ./hsh
rm a.out.txt
echo
echo
echo --------------------------------------------
echo "TEST: \"/bin/ls ls\""
echo "==========[sh]=========="
echo "/bin/ls ls" | sh
echo
echo "==========[hsh]========="
echo "/bin/ls ls" | ./hsh
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
