#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# ^C handling tests

echo "--------------------------------------------"
echo "----------- HANDLE ^C [TASK 10] -----------"
echo "--------------------------------------------"
echo
echo "TEST: Regular \"^C\""
echo "==========[sh]=========="
echo "^C" | sh
echo
echo "==========[hsh]========="
echo "^C" | ./hsh
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
