#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# PATH handling tests

echo "--------------------------------------------"
echo "--------- SETENV/UNSETENV [TASK 12] --------"
echo "--------------------------------------------"
echo
echo "TEST: \"setenv TEST values 1\""
echo "==========[sh]=========="
echo "setenv TEST values 1" | sh
echo
echo "==========[hsh]========="
echo "setenv TEST values 1" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"setenv\""
echo "==========[sh]=========="
echo "setenv" | sh
echo
echo "==========[hsh]========="
echo "setenv" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"setenv TEST NULL NULL\""
echo "==========[sh]=========="
echo "setenv TEST NULL NULL" | sh
echo
echo "==========[hsh]========="
echo "setenv TEST NULL NULL" | ./hsh
echo
echo --------------------------------------------
echo "TEST: \"setenv TEST values NULL\""
echo "==========[sh]=========="
echo "setenv TEST values NULL" | sh
echo
echo "==========[hsh]========="
echo "setenv TEST values NULL" | ./hsh
echo
echo
echo --------------------------------------------
echo "TEST: \"unsetenv\""
echo "==========[sh]=========="
echo "unsetenv" | sh
echo
echo "==========[hsh]========="
echo "unsetenv" | ./hsh
echo
echo
echo --------------------------------------------
echo "TEST: \"unsetenv HOME\""
echo "==========[sh]=========="
echo "unsetenv HOME" | sh
echo
echo "==========[hsh]========="
echo "unsetenv HOME" | ./hsh
echo
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
