#!/bin/bash
# Use these templates to format your test file.
# Your shell must be compiled as ./hsh to run these tests.
# TEMPLATE
# echo ==========[sh]========== <- denotes test with actual shell
# echo ls | sh
# echo
# echo ==========[hsh]========== <- denotes test with student shell
# echo ls | [your_compiled_shell_executable]
# echo
# PATH handling tests
echo ---------------------------------------------------
echo --------- HANDLE THE CD COMMAND [TASK 13] ---------
echo --------*******------------------------------------
echo
echo TEST: \cd\
echo ==========[sh]==========
echo cd | sh
echo
echo ==========[hsh]=========
echo cd | ./hsh
echo
echo --------------------------------------------
echo TEST: Trailing spaces \cd               \
echo ==========[sh]==========
echo cd                | sh
echo
echo ==========[hsh]=========
echo cd                | ./hsh
echo
echo --------------------------------------------
echo TEST: Leading spaces \               cd\
echo ==========[sh]==========
echo                cd | sh
echo
echo ==========[hsh]=========
echo                cd | ./hsh
echo
echo --------------------------------------------
echo TEST: Trailing tabs \\t\t\tcd"
echo ==========[sh]==========
echo \t\t\tcd | sh
echo
echo ==========[hsh]=========
echo \t\t\tcd | ./hsh
echo
echo
echo --------------------------------------------
echo TEST: Leading tabs \\t\t\tcd"
echo ==========[sh]==========
echo \t\t\tcd | sh
echo
echo ==========[hsh]=========
echo \t\t\tcd | ./hsh
echo
echo
echo --------------------------------------------
echo --------------- END OF TEST ----------------
echo --------------------------------------------