#!/bin/bash

# Use these templates to format your test file.
# Your shell must be compiled as "./hsh" to run these tests.

# TEMPLATE
# echo "==========[sh]==========" <- denotes test with actual shell
# echo "ls" | sh
# echo
# echo "==========[hsh]==========" <- denotes test with student shell
# echo "ls" | [your_compiled_shell_executable]
# echo

# VARIABLE handling tests

echo "--------------------------------------------"
echo "----------- NON-INTERACTIVE MODE -----------"
echo "--------------------------------------------"
echo
echo "TEST: Regular \"echo $$\""
echo "==========[sh]=========="
echo "echo $$" | sh
echo
echo "==========[hsh]========="
echo "echo $$" | ./hsh
echo
echo "TEST: Regular \"echo $?\""
echo "==========[sh]=========="
echo “echo $?" | sh
echo
echo "==========[hsh]========="
echo “echo $?" | ./hsh
echo
echo "TEST: Regular \"echo $PATH\””
echo "==========[sh]=========="
echo “echo $PATH" | sh
echo
echo "==========[hsh]========="
echo “echo $PATH" | ./hsh
echo --------------------------------------------
echo "TEST: Trailing spaces \"echo $$    \""
echo "==========[sh]=========="
echo "echo $$    " | sh
echo
echo "==========[hsh]========="
echo "echo $$    " | ./hsh
echo
echo "TEST: Trailing spaces \"echo $?    \""
echo "==========[sh]=========="
echo "echo $?    " | sh
echo
echo "==========[hsh]========="
echo "echo $?    " | ./hsh
echo
echo "TEST: Trailing spaces \"echo $PATH    \""
echo "==========[sh]=========="
echo "echo $PATH    " | sh
echo
echo "==========[hsh]========="
echo "echo $PATH    " | ./hsh
echo --------------------------------------------
echo "TEST: Leading spaces \"    echo $$\""
echo "==========[sh]=========="
echo "    echo $$" | sh
echo
echo "==========[hsh]========="
echo "    echo $$" | ./hsh
echo
echo "TEST: Leading spaces \"    echo $?\""
echo "==========[sh]=========="
echo "    echo $?" | sh
echo
echo "==========[hsh]========="
echo "    echo $?" | ./hsh
echo
echo "TEST: Leading spaces \"    echo $PATH\””
echo "==========[sh]=========="
echo "    echo $PATH” | sh
echo
echo "==========[hsh]========="
echo "    echo $PATH” | ./hsh
echo
echo --------------------------------------------
echo "TEST: Leading and trailing tabs \"\techo $$\t\""
echo "==========[sh]=========="
echo "\techo $$\t" | sh
echo
echo "==========[hsh]========="
echo "\techo $$\t" | ./hsh
echo
echo "TEST: Leading and trailing tabs \"\techo $?\t\""
echo "==========[sh]=========="
echo "\techo $?\t" | sh
echo
echo "==========[hsh]========="
echo "\techo $?\t" | ./hsh
echo
echo "TEST: Leading and trailing tabs \"\techo $PATH\t\””
echo "==========[sh]=========="
echo "\techo $PATH\t” | sh
echo
echo "==========[hsh]========="
echo "\techo $PATH\t” | ./hsh
echo
echo --------------------------------------------
echo "TEST: Multiple spaces and tabs \"\t   \t\t echo $$  \t\t  \t \""
echo "==========[sh]=========="
echo "\t   \t\t echo $$  \t\t  \t \"" | sh
echo
echo "==========[hsh]========="
echo "\t   \t\t echo $$  \t\t  \t \"" | ./hsh
echo
echo "TEST: Multiple spaces and tabs \"\t   \t\t echo $?  \t\t  \t \""
echo "==========[sh]=========="
echo "\t   \t\t echo $?  \t\t  \t \"" | sh
echo
echo "==========[hsh]========="
echo "\t   \t\t echo $?  \t\t  \t \"" | ./hsh
echo
echo
echo "TEST: Multiple spaces and tabs \"\t   \t\t echo $PATH  \t\t  \t \""
echo "==========[sh]=========="
echo "\t   \t\t echo $PATH  \t\t  \t \"" | sh
echo
echo "==========[hsh]========="
echo "\t   \t\t echo $PATH  \t\t  \t \"" | ./hsh
echo
echo "--------------------------------------------"
echo "--------------- END OF TEST ----------------"
echo "--------------------------------------------"
